project_id = "dplhklybfdkjpwzolkzs"

[functions.process-payment]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.kkiapay-webhook]
verify_jwt = false

[functions.send-article-notification]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-ad-cta]
verify_jwt = true

[functions.translate-product]
verify_jwt = true
