project_id = "dplhklybfdkjpwzolkzs"

[functions.process-payment]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.send-article-notification]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false
